// import {
//   Template1Preview,
//   Template2Preview,
//   Template3Preview,
//   Template4Preview,
//   Template5Preview,
//   Template6Preview,
//   Template7Preview,
//   Template8Preview,
//   Template9Preview,
//   Template10Preview,
//   Template11Preview,
// } from "../constants/templatePreviews.jsx";

// const templates = [
//   {
//     id: "template1",
//     name: "1 Simple Clean Dark",
//     price: 1,
//     features: ["Smooth fade-in scroll", "Gradient text hero", "Solid navbar"],
//     image: "/thumbs/t1.png",
//     demoUrl: "/templates/preview/template1",
//     component: Template1Preview,
//   },
//   {
//     id: "template2",
//     name: "2 Gradient Hero",
//     price: 399,
//     features: ["Animated gradient background", "Floating avatar", "Section transitions"],
//     image: "/thumbs/t2.png",
//     demoUrl: "/templates/preview/template2",
//     component: Template2Preview,
//   },
//   {
//     id: "template3",
//     name: "3 Split Hero Showcase",
//     price: 499,
//     features: ["Left image + right content", "Parallax scroll", "Interactive skill cards"],
//     image: "/thumbs/t3.png",
//     demoUrl: "/templates/preview/template3",
//     component: Template3Preview,
//   },
//   {
//     id: "template4",
//     name: "4 Neon Scroll-Snap",
//     price: 599,
//     features: ["Full-page snap scroll", "Glowing headings", "Neon hover cards"],
//     image: "/thumbs/t4.png",
//     demoUrl: "/templates/preview/template4",
//     component: Template4Preview,
//   },
//   {
//     id: "template5",
//     name: "5 Glassmorphism",
//     price: 699,
//     features: ["Frosted blur cards", "Hover depth effects", "Glowing buttons"],
//     image: "/thumbs/t5.png",
//     demoUrl: "/templates/preview/template5",
//     component: Template5Preview,
//   },
//   {
//     id: "template6",
//     name: "6 Horizontal Showcase",
//     price: 799,
//     features: ["Horizontal scroll projects", "Smooth snap", "Creative portfolio look"],
//     image: "/thumbs/t6.png",
//     demoUrl: "/templates/preview/template6",
//     component: Template6Preview,
//   },
//   {
//     id: "template7",
//     name: "7 Timeline Storytelling",
//     price: 899,
//     features: ["Animated left-right timeline", "Education + Experience", "Story/journey look"],
//     image: "/thumbs/t7.png",
//     demoUrl: "/templates/preview/template7",
//     component: Template7Preview,
//   },
//   {
//     id: "template8",
//     name: "8 Minimal White (Apple Style)",
//     price: 999,
//     features: ["White space", "Typography focus", "Recruiter-friendly"],
//     image: "/thumbs/t8.png",
//     demoUrl: "/templates/preview/template8",
//     component: Template8Preview,
//   },
//   {
//     id: "template9",
//     name: "9 3D Animated",
//     price: 1099,
//     features: ["Tilt hover effects", "Floating skill icons", "Depth transitions"],
//     image: "/thumbs/t9.png",
//     demoUrl: "/templates/preview/template9",
//     component: Template9Preview,
//   },
//   {
//     id: "template10",
//     name: "10 Ultra Premium (Luxury)",
//     price: 1199,
//     features: ["Parallax hero", "Cinematic bg", "Luxury wow-factor"],
//     image: "/thumbs/t10.png",
//     demoUrl: "/templates/preview/template10",
//     component: Template10Preview,
//   },
//   {
//     id: "template11",
//     name: "11 Diagonal Sections",
//     price: 1299,
//     features: ["Diagonal layouts", "Dynamic transitions", "Premium showcase"],
//     image: "/thumbs/t11.png",
//     demoUrl: "/templates/preview/template11",
//     component: Template11Preview,
//   },
// ];

// export default templates;

import {
  Template1Preview,
  Template2Preview,
  Template3Preview,
  Template4Preview,
  Template5Preview,
  Template6Preview,
  Template7Preview,
  Template8Preview,
  Template9Preview,
  Template10Preview,
  Template11Preview,
} from "../constants/templatePreviews.jsx";

const templates = [
  {
    id: "template1",
    name: "Modern Neon Dark",
    price: 299,
    features: ["Sticky navbar", "Neon headings", "Smooth fade animations", "Glowing skill orbs", "Resume download button"],
    image: "/thumbs/t1.png",
    demoUrl: "/templates/preview/template1",
    component: Template1Preview,
  },
  {
    id: "template2",
    name: "Gradient Glassmorphism",
    price: 399,
    features: ["Glassmorphism navbar", "Hero profile card", "Skills as icon pills", "Project grid", "Contact form"],
    image: "/thumbs/t2.png",
    demoUrl: "/templates/preview/template2",
    component: Template2Preview,
  },
  {
    id: "template3",
    name: "Split Hero Layout",
    price: 499,
    features: ["Split hero (image + text)", "Interactive skill cards", "Animated headings", "Tag-based projects", "Resume section"],
    image: "/thumbs/t3.png",
    demoUrl: "/templates/preview/template3",
    component: Template3Preview,
  },
  {
    id: "template4",
    name: "Minimal Clean Theme",
    price: 599,
    features: ["Blur navbar", "Hero with neon text", "Responsive links", "Projects with thumbnails", "Footer with credits"],
    image: "/thumbs/t4.png",
    demoUrl: "/templates/preview/template4",
    component: Template4Preview,
  },
  {
    id: "template5",
    name: "Premium Dark Glass",
    price: 699,
    features: ["Radial animated background", "Premium glass cards", "3D tilt project cards", "Resume download", "Blur footer"],
    image: "/thumbs/t5.png",
    demoUrl: "/templates/preview/template5",
    component: Template5Preview,
  },
  {
    id: "template6",
    name: "Diagonal Hero Light",
    price: 799,
    features: ["Diagonal hero", "Clean white theme", "Skills grid", "Projects showcase", "Footer with credits"],
    image: "/thumbs/t6.png",
    demoUrl: "/templates/preview/template6",
    component: Template6Preview,
  },
  {
    id: "template7",
    name: "Blob Background Portfolio",
    price: 899,
    features: ["Animated blob background", "Hero card with CTAs", "Grouped skill sets", "Projects & Education", "Minimal footer"],
    image: "/thumbs/t7.png",
    demoUrl: "/templates/preview/template7",
    component: Template7Preview,
  },
  {
    id: "template8",
    name: "Smooth Scroll Light/Dark",
    price: 999,
    features: ["Light/Dark theme toggle", "Solid navbar on scroll", "Animated avatar", "Projects grid", "Contact with form + info"],
    image: "/thumbs/t8.png",
    demoUrl: "/templates/preview/template8",
    component: Template8Preview,
  },
  {
    id: "template9",
    name: "Clean Resume Style",
    price: 1099,
    features: ["Rotating avatar animation", "Resume download", "Experience/Education cards", "Skills grouped by type", "Contact info with location"],
    image: "/thumbs/t9.png",
    demoUrl: "/templates/preview/template9",
    component: Template9Preview,
  },
  {
    id: "template10",
    name: "Professional Gradient",
    price: 1199,
    features: ["Sticky solid navbar", "Theme toggle", "Gradient text hero", "Animated skills", "Project showcase"],
    image: "/thumbs/t10.png",
    demoUrl: "/templates/preview/template10",
    component: Template10Preview,
  },
  {
    id: "template11",
    name: "Dark Premium Motion",
    price: 1299,
    features: ["Dark/Light toggle", "Framer motion animations", "Rotating avatar", "Certifications list", "Resume + Contact sections"],
    image: "/thumbs/t11.png",
    demoUrl: "/templates/preview/template11",
    component: Template11Preview,
  }
];

export default templates;
